### ISSUE TITLE
[要望] 設定をテキストファイル等にバックアップできるようにして欲しい

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#10]
[Gesturefy](https://addons.mozilla.org/ja/firefox/addon/gesturefy/) というマウスジェスチャーアドオンではJSON形式で設定を保存して
保存したJSONを復元する機能があり、それと同じような機能をお願いします。

実装できたら他のパソコンや Mozilla Firefox ←→ Google Chrome で色などの設定を
簡単に同一にするのができると思います。

**Comment by arigayas** [comment]
デザインの参考としてGesturefy の設定画面のスクリーンショットを。


![image](https://user-images.githubusercontent.com/11251874/108607663-03107200-7405-11eb-9bef-8fbc4a860f06.png)

**Comment by hukihamu** [comment]
@arigayas 
0.4.3にて追加しました。ご確認ください。

**Comment by arigayas** [comment]
Firefox Developer EditionでJSONファイル形式で設定をエクスポートして
Firefox ESR版でインポート出来ました！

Google Chromeをインストールしていないので
Google Chrome→Firefox やその逆をテストしてないのですがCloseします。
