### ISSUE TITLE
[要望] ニコレポページの各項目の「??時間前」の赤字を無効にできるようにして欲しい

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#11]
特にニコニコ生放送の番組は始まって2時間以上前の配信って半分以上は終了していることが多いので
赤字にする必要性がない気がするので要望を書きました。

この赤字は最大23時間前のようです。
![image](https://user-images.githubusercontent.com/11251874/107691399-bc2cc900-6cee-11eb-8e76-98fe6e796038.png)

### 仕様

- 設定画面で「??」時間以上前の赤字無効にする。
- 「??」の部分は、プルダウンメニューで数字[0～23]を設定する。
- 0の場合は全ての時間を赤字のままにする。(= つまり何も変更しない。)

**Comment by hukihamu** [comment]
https://github.com/hukihamu/HamNicoVideo/releases/tag/0.4.6 で対応しましたので、クローズとします。

**Comment by arigayas** [comment]
ありがとうございます。
色変更出来ました！！
