### ISSUE TITLE
[要望] アドオンのアイコンをURLがニコニコの時だけ表示するようにして欲しい

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#12]
[Twitter Web に対するアドオン](https://addons.mozilla.org/ja/firefox/addon/twitter-old-ui/)がTwitterのドメインの時だけアドオンのアイコンを表示するようにしています。
![image](https://user-images.githubusercontent.com/11251874/108325254-3f2cb280-720c-11eb-98e0-cc978b6572a0.png)

[Niconico Downloader](https://addons.mozilla.org/ja/firefox/addon/niconico-downloader/) も同じような機能を持ってます。

**Comment by hukihamu** [comment]
現行仕様だと必要ないと判断したためCloseとします
