### ISSUE TITLE
[要望]設定の意味が分かるドキュメントが欲しい

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#13]
設定画面の各項目を説明したドキュメントをスクリーンショット付きで作ってほしいです。
特に「再生画面」の部分です。

### 再生画面
CUSTOM_MY_LIST
ENABLE
MY_LIST_ID
HIDE_WATCH_LATER
HOLD_SETTING
ENABLE
CONTINUOUS
ENABLE
HOLD_VALUE
PLAYBACK_RATE
ENABLE
HOLD_VALUE
PLAYER_CONTROLLER
ENABLE
HOLD_VALUE
IS_HTTP_VIDEO

**Comment by hukihamu** [comment]
@arigayas 
0.4.3にて修正しました。ご確認ください。

**Comment by arigayas** [comment]
0.4.3 にバージョンアップされたことで設定画面が日本語になったので、
ほとんどの機能がわかるようになりましたが
次の2点がよくわからないのです。

- 「カスタムマイリスト」について
- 「カスタムマイリスト」の配下の「マイリストID」の「数値」の意味

Wikiにて解説をお願いします。

**Comment by hukihamu** [comment]
取り急ぎ作成しました。

https://github.com/hukihamu/HamNicoVideo/wiki/%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3

**Comment by hukihamu** [comment]
一旦完了ということで。クローズとします。
Wiki関連は、以下Issueにお願いします。

https://github.com/hukihamu/HamNicoVideo/issues/19

**Comment by arigayas** [comment]
~ありがとうございます。~
了解しました。
