### ISSUE TITLE
[バグ]各種機能が正常に動作しない

### ISSUE THREAD

**Issue by hukihamu** [hukihamu/HamNicoVideo#16]
最近のアップデートで、URLが変更されたようです。

調査、修正します。

**Comment by arigayas** [comment]
あとから確認する時にどこが正常に動作しないのかわかりにくいと思うので
面倒くさくても、どの機能が動作しないって列挙しておくと良いと思います。

**Comment by hukihamu** [comment]
0.4.4にてURLの更新をしました。


が、「いいね」レイアウトが変更されたので、要検討です...

**Comment by arigayas** [comment]
関連するリリースはこれでしょうか？
[【3/18追記】「いいね！」数の表示について【ニコニコ動画】｜ニコニコインフォ](https://blog.nicovideo.jp/niconews/146496.html#watchlater)

**Comment by hukihamu** [comment]
修正済みのためCloseします
