### ISSUE TITLE
[要望] ニコレポページの「フィルター」機能で「？？？ さんにフォローされました」を追加して欲しい

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#18]
機能の追加し忘れだと思うので
ニコレポページの「フォローされた通知」を「フィルター」で非表示出来るようになって欲しいと思いました。

**Comment by arigayas** [comment]
Ver0.4.7での追加作業お疲れさまです。

Firefox にて確認しましたが

ニコレポページの「フィルタ」名が「undefined」になってます。
![image](https://user-images.githubusercontent.com/11251874/120886254-f1578100-c627-11eb-8529-ce7399f1d8ed.png)

### 設定画面だと英字になってます。
![image](https://user-images.githubusercontent.com/11251874/120886303-354a8600-c628-11eb-9ca6-18f32c6e8843.png)

**Comment by hukihamu** [comment]
@arigayas   
問題報告ありがとうございます。  
新機能追加のついでに修正しますので、今しばらくお待ちを。。。

**Comment by arigayas** [comment]
了解しました。

**Comment by arigayas** [comment]
Ver.0.5.0 で修正を確認しました。
動作チェック(*)はしてませんがCloseします。

*： 「ニコレポ」ページで「フォロー通知」のチェックボックスのオンオフすること。
