### ISSUE TITLE
Firefox 版が公開されてません

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#4]
Firefox 版を依頼した者です。
作成依頼してから数日経ったのに[アドオンの配布ページ](https://addons.mozilla.org/ja/firefox/addon/ham-nicovideo/)を開いても「申し訳ございません。ページを見つけることができませんでした。」と表示されます。

現状、どうなっているのか確認をお願いします。

**Comment by hukihamu** [comment]
@arigayas 
ご報告、ありがとうございます。
確認したところ、審査待ち(記入漏れの指摘)となっていました。
記入漏れの修正を済ませていましたが、Firefoxに届いてなく、審査が滞っていたようです..

再審査の旨を送ったので、いずれ公開されるかと思われます。

追記：「審査待ちの順番: 70 個中 9 個目」とのこと

**Comment by arigayas** [comment]
@hukihamu 
確認していただきありがとうございます。
3日ぐらい待ってみますね。

**Comment by hukihamu** [comment]
@arigayas 

https://addons.mozilla.org/ja/firefox/addon/ham-nicovideo/
利用できるようになったようです。

**Comment by arigayas** [comment]
公開されたことを確認したので閉じます。
