### ISSUE TITLE
マイページの最新ニコレポ ページのフィルターで生放送にチェックを入れても予約された番組が非表示になりません。

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#5]
使用バージョン：0.3.1

マイページの最新ニコレポ ページのフィルターで`生放送`にチェックを入れても「予約された番組」が非表示になりません。

チェックを入れたら「予約された番組」が非表示になることを期待します。

**Comment by hukihamu** [comment]
不具合のご報告、ありがとうございます。
「修正対応」に追加しました。

**Comment by hukihamu** [comment]
[0.3.2](https://github.com/hukihamu/HamNicoVideo/releases/tag/0.3.2)で対応しました。
