### ISSUE TITLE
Firefox ： マイページの最新ニコレポ ページのフィルターが追加(表示)されない

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#6]
使用バージョン：0.3.2

再現方法不明ですがフィルター機能が表示されなくなりました。

**Comment by hukihamu** [comment]
ご報告、ありがとうございます。

高確率で発生するのであれば修正します。が、今後ニコレポ画面に大きく手を加える予定ですので、待てるのであれば待っていただければ...

**Comment by arigayas** [comment]
> 高確率で発生するのであれば修正します。が、今後ニコレポ画面に大きく手を加える予定ですので、待てるのであれば待っていただければ...

高確率というか発生するとずっとフィルターが表示されない気がします😭
大改造予定ということで待ちますね。

別のissueとして登録すべきですが、
マイページの最新ニコレポ ページのHighlight機能がHamNicoVideoをインストールしてから一度も機能してない気がします。

**Comment by arigayas** [comment]
再現方法は「ページの再読込」かもしれません。

しかし、フィルターが表示されない場合に何度か再読込すると表示されます。

**Comment by arigayas** [comment]
恐らくVer.0.4.2で修正されたのでCloseします。

**Comment by arigayas** [comment]
ニコレポページを再読込するとフィルターのリスト部分が消えることが多々あるのでReopenします。

使用Ver：Firefox 版の0.4.2

**Comment by arigayas** [comment]
高確率で再現する方法を2つ見つけたっぽいので書き残しておきます。
![image](https://user-images.githubusercontent.com/11251874/108323851-82862180-720a-11eb-8b27-c804b3ba8f76.png)

### その1

1. [ニコレポ](https://www.nicovideo.jp/my/nicorepo) を開きます。
2. 「タイプ」は恐らく「すべて」が選択されていると思うので、そこから「動画投稿」や「生放送開始」など「すべて」以外を選択します。
3. ページの再読込を実行します。
4. フィルターのリスト部分が高確率で消えます。

### その2
1. [ニコレポ](https://www.nicovideo.jp/my/nicorepo) を開きます。
2. 「表示対象」は恐らく「すべて」が選択されていると思うので、そこから「自分」や「ユーザー」など「すべて」以外を選択します。
3. ページの再読込を実行します。
4. フィルターのリスト部分が高確率で消えます。

両方共にURLが変更されるのですがこれは要因になるのでしょうか？

**Comment by hukihamu** [comment]
@arigayas  
ご報告ありがとうございます。

> 高確率で再現する方法を2つ見つけたっぽいので書き残しておきます。

タイプや表示対象によるイベント取得し忘れてますねこれは...   
また、`https://www.nicovideo.jp/my/nicorepo`だとurl的に対象外になってますね...  
手が空けば修正します。

**Comment by arigayas** [comment]
> ご報告ありがとうございます。
> 
> > 高確率で再現する方法を2つ見つけたっぽいので書き残しておきます。
> 
> タイプや表示対象によるイベント取得し忘れてますねこれは...
> また、`https://www.nicovideo.jp/my/nicorepo`だとurl的に対象外になってますね...
> 手が空けば修正します。

了解しました。

**Comment by hukihamu** [comment]
@arigayas 
0.4.3にて修正しました。ご確認ください。

**Comment by arigayas** [comment]
恐らくこのバグは再現しなくなりましたが様子見します・・・。
