### ISSUE TITLE
要望：設定画面のVALUE_HIGHLIGHTの各項目にエラーチェック機能を入れて欲しい

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#7]
Firefox版 Ver.0.3.2を使ってます。

要望は2つです。
1つ目：
設定画面のVALUE_HIGHLIGHTの各項目にカラーコードかどうかチェックする機能を入れて欲しいです。
間違った値(例：`#FFFFFFあ`)を入れても保存されたので
間違った値だった場合、
Plan A：「間違った値が入ってます」とエラーメッセージを表示する。もし無視して設定画面を閉じたらデフォルトの値にする。
Plan B：入力した値を赤文字にするか入力欄の背景色を黄色にする。もし無視して設定画面を閉じたらデフォルトの値にする。

2つ目：
値が保存されたら他の項目と同じく「保存されました」って表示して欲しいです。

質問です。
`#FFFFFF` を `#FFF` としても背景色(強調表示)は変わるのでしょうか？

出来ればUIから色を選べたらうれしいです。
![image](https://user-images.githubusercontent.com/11251874/99868946-7ccc7000-2c0a-11eb-8835-5e6d04098135.png)

**Comment by hukihamu** [comment]
ご要望ありがとうございます。

> 設定画面のVALUE_HIGHLIGHTの各項目にカラーコードかどうかチェックする機能を入れて欲しいです。
> 出来ればUIから色を選べたらうれしいです。

chrome版ではjscolorを導入しましたので、色選択が用意になるかと。  
ただ、firefox版ではjscolorの導入が不可能な様ですので、書式チェックは後々追加します...

> 値が保存されたら他の項目と同じく「保存されました」って表示して欲しいです。

v0.3.2のバグで、単純に保存されていませんでした...   
v0.4.0以降では修正されていますので、ご確認ください。

> #FFFFFF を #FFF としても背景色(強調表示)は変わるのでしょうか？

styleに値を入れているだけですので、動くはずです。(カラーネームも動くはず)

**Comment by arigayas** [comment]
> ご要望ありがとうございます。
> 
> > 設定画面のVALUE_HIGHLIGHTの各項目にカラーコードかどうかチェックする機能を入れて欲しいです。
> > 出来ればUIから色を選べたらうれしいです。
> 
> chrome版ではjscolorを導入しましたので、色選択が用意になるかと。
> ただ、firefox版ではjscolorの導入が不可能な様ですので、書式チェックは後々追加します...

追加されるのを待ってます。


> > 値が保存されたら他の項目と同じく「保存されました」って表示して欲しいです。
> 
> v0.3.2のバグで、単純に保存されていませんでした...
> v0.4.0以降では修正されていますので、ご確認ください。

修正されたのを確認しました。


> > #FFFFFF を #FFF としても背景色(強調表示)は変わるのでしょうか？
> 
> styleに値を入れているだけですので、動くはずです。(カラーネームも動くはず)

#ddd としても設定出来ることを確認しました。

**Comment by hukihamu** [comment]
@arigayas 
0.4.3にてpatternではありますが追加しました。ご確認ください。

**Comment by arigayas** [comment]
Firefox でpatternに一致しない場合、入力欄が赤枠表示になるだけで、設定として保存されます。
![image](https://user-images.githubusercontent.com/11251874/108610071-1415af00-7416-11eb-88a1-b9eface41045.png)


ニコレポページでは背景色は色設定がデフォルトの白になります。
動作としては致命的エラーではないのでCloseします。
