### ISSUE TITLE
Firefox版のHamNicoVideo ver. 0.4.0 の設定画面を開くとスクロールバーが縦にドンドン伸びていきます。

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#8]
症状を見る感じ無限ループっぽいです。

1. Firefox のアドオンマネージャを開きます。
2. HamNicoVideo をクリックします。
3. オプションをクリックします。
4. スクロールバーが縦にドンドン伸びていきます。

期待する結果：

4. スクロールバーが縦にドンドン伸びずに設定を見ることが出来る。

**Comment by hukihamu** [comment]
バグ報告ありがとうございます。

オプション画面の問題、確認しました。
おそらく、chrome版のように、新しいタブでオプション画面が表示されないことが原因でした。

ですので、修正した0.4.1を上げましたので、ご確認ください。

**Comment by arigayas** [comment]
別タブで開かれるようになったのを確認したのでCloseします。
修正お疲れさまでした。
