### ISSUE TITLE
[Firefox] オプションページのタイトルとページ内のタイトルが違う

### ISSUE THREAD

**Issue by arigayas** [hukihamu/HamNicoVideo#9]
些細なことですが、オプションページのタイトル[`HamNicoOptions`]と
ページ内のタイトル[`HamVideo Option`]が違うのが気になります。

使用バージョン：
Firefox版 Ver.0.4.2

**Comment by hukihamu** [comment]
@arigayas 
0.4.3にて修正しました。ご確認ください。

**Comment by arigayas** [comment]
修正を確認しました。
